### ISSUE TITLE
Implement payMana() for a list of mana tokens

### ISSUE THREAD

**Issue by Stoeoef** [MartinAltmayer/mageknight#29]
Often, we need to pay several mana tokens at once. Very often there are multiple ways to pay the first token, but just one way for the following ones. A sneaky algorithm could deduce this to a certain extent.
An example: Only a blue token and a blue mana crystal are available (the source is used). In this case,
 ```
payMana(Mana.blue)
payMana(Mana.blue)
```
would first open a dialogue which is not necessary from the player's point of view

**Comment by MartinAltmayer** [comment]
The only situation which come to my mind is paying for a strong spell. Except for rare cases, it is always clear how to pay the black mana, so this case basically reduces to the normal case.

**Comment by MartinAltmayer** [comment]
payMana now supports specifying multiple mana colors (used by strong spells, altars, Altem Mages middle ability). No sneaky algorithm has been implemented, because situations in which this applies are rare and such and algorithm is difficult to get right with all mana providers and converters.

But feel free to try ;-)
