### ISSUE TITLE
Implement resting and slow recovery.

### ISSUE THREAD

**Issue by Stoeoef** [MartinAltmayer/mageknight#44]

**Comment by Stoeoef** [comment]
@MartinAltmayer : Am i forced to use slow recovery If I start the turn with only wound cards on my hand (assuming I cannot announce the end of round)? The rules don't explicitly say so, If I read them right, though it's the most logical interpretation I think, as you cannot discard a card at the end of your turn.

**Comment by MartinAltmayer** [comment]
In https://boardgamegeek.com/article/7549018#7549018 Vlaada stated that you have to decide whether you do a rest at the beginning of your turn (though the actual resting might be done later in the turn). 

Some writers on Boardgamegeek suggest that you are allowed to play a regular turn if you will be able to discard a card via a skill or similar this turn. I am pretty sure that there is no rule that depends on future events in this way.

Thus I support the ruling that you have to do a Rest turn if you have only wounds at the beginning of your turn.

**Comment by MartinAltmayer** [comment]
Ok, I just read the expansion rules. They clearly state that you do not need to decide whether you do a regular turn or a rest at the beginning of your turn. You simply can do a rest as long as you did not play movement/influence/combat effects or start an action.

So forget the previous post :-)

**Comment by MartinAltmayer** [comment]
Reading the "Turn sequence overview" of the expansion, I'd say that nothing forces you to do a rest.

**Comment by MartinAltmayer** [comment]
Based on the expansion rules I propose the following simple solution:
- We consider "Rest" as an action (like e.g. combat).
- You cannot choose the "Rest" action after you played a movement, influence or combat effect.
- You cannot choose the "Rest" action if you have no wounds on your hand (the only reason for this rule is to avoid having a useless "Rest" button in the GUI all the time).
- Whether the action starts a Standard Rest or a Slow Recovery is determined by the contents of your hand in the moment you start the action.

Note that because rest is considered an action, resting will put the game into state 'afterAction', where you can only play special and healing actions.
Also note that with these rules you are not forced to do a rest.

While the expansion rules do not consider rest to be an action, I think that this is the simplest way to implement rules consistent with the expansion.

**Comment by Stoeoef** [comment]
Seems legit.
